apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: argo-supply-chain-security.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Provide supply chain security to artifacts built with argo workflows
  displayName: argo-slsa
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - DevSecOps
  links:
  - name: Argo Supply Chain Security
    url: https://argo-supply-chain-security.domain
  maintainers:
  - email: 1234thariq@gmail.com
    name: MohomedThariq
  maturity: alpha
  provider:
    name: Mohomed Thariq
  version: 0.0.0
