apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: argo-supply-chain-security
    app.kubernetes.io/managed-by: kustomize
data:
  # following signing options are available
  # cosign, kms, fulcio
  artifacts.signer: cosign
  signer.transparency.enabled: "true"
  sbom.generation.enabled: "true"
